const ProgrammeActionTypes = {
  GET_PROGRAMMES_START: 'GET_PROGRAMMES_START',
  GET_PROGRAMMES_SUCCESS: 'GET_PROGRAMMES_SUCCESS',
  GET_PROGRAMMES_FAILURE: 'GET_PROGRAMMES_FAILURE',
};

export default ProgrammeActionTypes;
