/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:4804269b-48ac-442f-91b0-f7588b08fe6a",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_MaZz1SOQD",
    "aws_user_pools_web_client_id": "6a9554lkh3picu14lkl55s32kf",
    "oauth": {
        "domain": "thetraininggroundeastlondon-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3001/",
        "redirectSignOut": "http://localhost:3001/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "ttgelweb5a8b674e7fc14a7eae02eadb0a75fdb1230810-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
